### ISSUE TITLE
Dataset release date

### ISSUE THREAD

**Issue by xmba15** [YushengWHU/Railroad-dataset#1]
Hi @YushengWHU , thank you for making the dataset public.
When will (some sequences of) the dataset be released?

**Comment by YushengWHU** [comment]
> Hi @YushengWHU , thank you for making the dataset public. When will (some sequences of) the dataset be released?

Thank you for your consideration， we are now dealing with some law issues, and we hope we can finish these issues these days.

**Comment by xmba15** [comment]
@YushengWHU Just would like to check on the progress again.

**Comment by junzhang2016** [comment]
@YushengWHU Would like to enquire  the dataset release date as well.

**Comment by YushengWHU** [comment]
Dear all, sorry for the late reply, I have updated the links and codes for the dataset, if you have any problems downloading the datasets, you can contact me immediately.

**Comment by sunnytt98** [comment]
> Dear all, sorry for the late reply, I have updated the links and codes for the dataset, if you have any problems downloading the datasets, you can contact me immediately.

@YushengWHU  您好，数据集的百度网盘链接失效了，您可以重新发一下吗？

**Comment by YushengWHU** [comment]
> > Dear all, sorry for the late reply, I have updated the links and codes for the dataset, if you have any problems downloading the datasets, you can contact me immediately.
> 
> @YushengWHU 您好，数据集的百度网盘链接失效了，您可以重新发一下吗？

全部重新发了你看看
